### ISSUE TITLE
My goals and progress

### ISSUE THREAD

**Issue by hapnait** [Ludeon/RimWorld-Thai#1]
**_Update 2020-03:_**

_List below now mostly corrected to some extend, for now I just adding new translations to the files that marked done, this list will update as it should be after that._

_btw, I'm very glad that I made this lists when I'd started working on this, or I'll never remember what is what in the progress. lol_

--------------------

This is an issue to track what progress I've made, will be updating this regularly while working on translation.

## Goals
a 'what I want to get done' list

#### Will do
- ✅ Clean-up to be compatible with RimWorld 1.1
- 🔲 Checking consistency of translation, to be certain quality, to not confuse players.
- 🔲 Translate all of `DefInjected`.
- ✅ Translate all of `Keyed`.
- 🔲 Translate necessary `Strings` (at least that is used in RulesStrings, RulePack list).

#### Maybe or maybe not
- Still don't know will I have time and energy to translate `Backstories`

## In-Progress

These are partly done:

* `TraitDef` translated all TODO, not checking any exist translation yet.
* `ThingDef` translated only Label, leave Description for later.
* I did not touch any of these yet: `ConceptDef`, `InstructionDef`, `TaleDef`, `ThoughtDef`

### Check list (outdated)
In list below, *Checked Box* mean: It's done, all translated and aligned nicely with other part of translation.

- 🔲 DefsInjected
    - [x] ApparelLayerDef
    - [x] BillRepeatModeDef
    - [x] BillStoreModeDef
    - [x] BiomeDef
    - [x] BodyDef
    - [x] BodyPartDef
    - [x] BodyPartGroupDef
    - [x] ChemicalDef
    - [ ] ConceptDef
    - [x] DamageDef
    - [x] DesignationCategoryDef
    - [x] DifficultyDef
    - [x] ExpectationDef
    - [x] FactionDef
    - [x] GameConditionDef
    - [x] HairDef
    - [x] HediffDef
    - [x] HediffGiverSetDef
    - [x] HistoryAutoRecorderDef
    - [x] HistoryAutoRecorderGroupDef
    - [x] IncidentDef
    - [x] InspirationDef
    - [ ] InstructionDef
    - [ ] InteractionDef
    - [x] JobDef
    - [x] JoyKindDef
    - [x] KeyBindingCategoryDef
    - [x] KeyBindingDef
    - [x] LifeStageDef
    - [x] MainButtonDef
    - [x] MentalBreakDef
    - [x] MentalStateDef
    - [x] NeedDef
    - [x] PawnCapacityDef
    - [x] PawnColumnDef
    - [x] PawnKindDef
    - [x] PawnRelationDef
    - [x] PawnsArrivalModeDef
    - [x] PrisonerInteractionModeDef
    - [x] RaidStrategyDef
    - [x] RecipeDef
    - [x] RecordDef
    - [x] ResearchProjectDef
    - [x] ResearchTabDef
    - [x] RiverDef
    - [x] RoadDef
    - [x] RoofDef
    - [x] RoomRoleDef
    - [x] RoomStatDef
    - [ ] RulePackDef
    - [x] ScenarioDef
    - [x] ScenPartDef
    - [x] SiteCoreDef
    - [x] SitePartDef
    - [x] SkillDef
    - [x] SpecialThingFilterDef
    - [x] StatCategoryDef
    - [x] StatDef
    - [x] StorytellerDef
    - [x] StuffCategoryDef
    - [ ] TaleDef
    - [x] TerrainAffordanceDef
    - [x] TerrainDef
    - [x] ThingCategoryDef
    - [ ] ThingDef
    - [ ] ThoughtDef
    - [x] TimeAssignmentDef
    - [x] ToolCapacityDef
    - [x] TraderKindDef
    - [x] TrainabilityDef
    - [x] TrainableDef
    - [ ] TraitDef
    - [x] TransferableSorterDef
    - [x] WeatherDef
    - [x] WorkGiverDef
    - [x] WorkTypeDef
    - [x] WorldObjectDef
- ✅ Keyed
    - [x] Alerts.xml
    - [x] Credits.xml
    - [x] Dates.xml
    - [x] Designators.xml
    - [x] Dialogs_Various.xml
    - [x] Dialog_StatsReports.xml
    - [x] Dialog_Trees.xml
    - [x] Enums.xml
    - [x] FloatMenu.xml
    - [x] GameplayCommands.xml
    - [x] Grammar.xml
    - [x] Incidents.xml
    - [x] ITabs.xml
    - [x] Letters.xml
    - [x] MainTabs.xml
    - [x] Menus_Main.xml   
    - [x] Menu_KeyBindings.xml
    - [x] Menu_Options.xml
    - [x] Messages.xml
    - [x] Misc.xml
    - [x] Misc_Gameplay.xml
    - [x] PlayInterface.xml
    - [x] ScenParts.xml
    - [x] Skills.xml
    - [x] Time.xml
    - [x] WITabs.xml
    - [x] WorkTags.xml
- 🔲 Strings

**Comment by ThoraninC** [comment]
Excuse me are you native Thai? or foreigner who has learned Thai.

So I can decide what language to communicate in file and comment in my translation.

**Comment by hapnait** [comment]
I'm Thai native speaker, you can use either English or Thai comments I'm okay with it.

ผมเขียนข้อมูลเป็นภาษอังกฤษนี่ ตั้งใจให้ทีมผู้พัฒนาเกมได้เห็นความคืบหน้าด้วยครับ แหะๆ เพราะทีแรกยังไม่เห็นคนอื่นมาร่วมแปล :)

ยังไงก็ตาม ยินดีต้อนรับ และขอบคุณไว้ก่อนครับ ที่มาลงแรงช่วยแปล 😃

**Comment by nicesafaleen** [comment]
ผมลองแปลไปสองสามอัน ถ้าไม่ดีใช้ commit ก่อนหน้าได้เลยครับ

**Comment by hapnait** [comment]
@nicesafaleen สวัสดีและขอบคุณครับที่มาช่วยแปลครับ

คำแปลใช้ได้ครับ ถ้าอ่านเข้าใจได้โดยใจความหลักยังคงเดิม สามารถใช้ได้หมดครับ ด้านสำนวนผมยังไงก็ได้มากถ้าอ่านแล้วไม่งง

แปลต่อไปและ push ขึ้นเรื่อยๆเลยครับ :D

ส่วนความคืบหน้าของผมตอนนี้: Backstories ผมยังไม่ได้แตะเหมือนเดิม ผมจะทำ Keyed ให้เสร็จและไปลุย DefInjected ต่อ ซึ่งมัน context based เอามากๆ ใช้เวลาเยอะในการแปลให้เหมาะกับบริบท
